"""
xml2md - Convert JUnit XML test reports to beautiful Markdown reports.

This utility parses JUnit XML format test reports (generated by pytest)
and creates nicely formatted Markdown reports with summary statistics
and detailed test results.

Usage:
    uv run xml2md report.xml                    # Output to report.md
    uv run xml2md report.xml -o custom.md       # Custom output path
    uv run xml2md report.xml --output results/  # Output to directory
"""

from .models import TestCase, TestSuite
from .parser import parse_junit_xml
from .formatter import format_duration, get_status_emoji, generate_markdown
from .cli import main

__all__ = [
    "TestCase",
    "TestSuite",
    "parse_junit_xml",
    "format_duration",
    "get_status_emoji",
    "generate_markdown",
    "main",
]
